#!/usr/bin/env bash
#script by Cuc

#monitor=eDP-1,1920x1200@60.0,1920x0,1.0
#monitor=HDMI-A-1,1920x1080@60.0,0x0,1.0

echo "#Generated by Cuc at $(date)" > $HOME/.config/hypr/monitors.conf
if  [[ -n $(hyprctl monitors | grep HDMI) ]]
then
    echo "monitor=eDP-1,disabled" >> $HOME/.config/hypr/monitors.conf
    echo "monitor=HDMI-A-1,1920x1080@60.0,0x0,1.0" >> $HOME/.config/hypr/monitors.conf
    echo "HDMI mode"
else
    echo "monitor=eDP-1,1920x1200@60.0,1920x0,1.0" >> $HOME/.config/hypr/monitors.conf
    echo "monitor=HDMI-A-1,disabled" >> $HOME/.config/hypr/monitors.conf
    echo "Laptop mode"
fi
