[FileDialog]
history=file:///home/cuc/Downloads/Telegram Desktop, file:///home/cuc/Pictures/toilet, file:///home/cuc, file:///home/cuc/Pictures/Screenshots, file:///home/cuc/Pictures
lastVisited=file:///home/cuc/Pictures
qtVersion=6.10.2
shortcuts=file:, file:///home/cuc
sidebarWidth=124
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2\xbd\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x1\x30\0\0\0\x1\0\0\0\0\0\0\0i\0\0\0\x1\0\0\0\0\0\0\0i\0\0\0\x1\0\0\0\0\0\0\0\xbb\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)
viewMode=Detail
