
source = $HOME/.config/hypr/variables.conf

source = $HOME/.config/hypr/configs/autostart.conf

source = $HOME/.config/hypr/configs/decoration.conf

source = $HOME/.config/hypr/configs/environments.conf

source = $HOME/.config/hypr/configs/input.conf

source = $HOME/.config/hypr/configs/keybinds.conf

source = $HOME/.config/hypr/configs/permissions.conf

source = $HOME/.config/hypr/configs/windowrules.conf

#source = $HOME/.config/hypr/monitors.conf

#source = $HOME/.config/hypr/workspaces.conf
