# ~/.config/hypr/hyprlock.conf

general {
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 5
    brightness = 0.5
    noise = 0.05
    contrast = 0.9
}

shape {
    monitor =
    size = 450, 550
    rounding = 20
    border_size = 2
    border_color = rgba(89b4fa88)
    color = rgba(1e1e2eaa)
    position = 0, -30
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = 90
    font_family = JetBrains Mono Bold
    color = rgba(cdd6f4ff)  # Catppuccin/нейтральный белый
    position = 0, 40
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"
    font_size = 22
    font_family = JetBrains Mono
    color = rgba(a6adc8ff)
    position = 0, -30
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:5000] bash -c 'b=$(cat /sys/class/power_supply/BAT0/capacity); s=$(cat /sys/class/power_supply/BAT0/status); if [ "$s" = "Charging" ]; then echo "󰂄 ${b}%"; elif [ $b -ge 80 ]; then echo "󰁹 ${b}%"; elif [ $b -ge 60 ]; then echo "󰂁 ${b}%"; elif [ $b -ge 40 ]; then echo "󰁿 ${b}%"; elif [ $b -ge 20 ]; then echo "󰁽 ${b}%"; else echo "󰁻 ${b}%"; fi'
    font_size = 22
    font_family = JetBrains Mono Nerd Font
    color = rgba(a6adc8ff)
    position = 0, -150
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 280, 55
    outline_thickness = 2
    rounding = 12

    outer_color = rgba(313244ff)
    inner_color = rgba(1e1e2eff)
    font_color = rgba(cdd6f4ff)

    check_color = rgba(f9e2afff)          # цвет пока проверяет пароль
    fail_color = rgba(f38ba8ff)           # цвет рамки при ошибке
    fail_text = <i>$FAIL ($ATTEMPTS)</i>  # текст ошибки, $ATTEMPTS — счётчик попыток
    fail_transition = 100                 # ms перехода к fail_color

    placeholder_text = <i>Пароль...</i>
    dots_size = 0.3
    dots_spacing = 0.2
    dots_center = true
    fade_on_empty = true

    position = 0, -220
    halign = center
    valign = center
}

image {
    monitor =
    path = /home/cuc/.face
    size = 250
    rounding = -1
    border_size = 2
    border_color = rgba(89b4faff)
    position = 0, 250
    halign = center
    valign = center
}
