
$term = kitty
$FM = yazi
$menu = rofi
$browser = zen-browser

$gapsi = 5
$gapso = 10
$bsize = 2
$acolor = rgba(33ccffee) rgba(00ff99ee) 45deg
$icolor = rgba(595959aa)

$sens = 0.2
$numlock = true
$left_handed = false
$nscroll = true

$mainMod = SUPER
$scriptsDir = $HOME/.config/hypr/scripts
$UserConfigs = $HOME/.config/hypr/UserConfigs
$UserScripts = $HOME/.config/hypr/UserScripts
