# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #B0E4F3
background         #1E1D28
cursor             #5D81A5

active_tab_foreground     #1E1D28
active_tab_background     #B0E4F3
inactive_tab_foreground   #B0E4F3
inactive_tab_background   #1E1D28

active_border_color   #B0E4F3
inactive_border_color #1E1D28
bell_border_color     #07123C

color0      #45434F
color1		#07123C
color2		#081541
color3		#183F80
color4		#1C4A8F
color5		#6376A5
color6		#1686A5
color7		#86D1E5
color8		#5D92A0
color9		#091850
color10		#0B1D57
color11		#2154AA
color12		#2662BF
color13		#849DDC
color14		#1DB3DC
color15		#86D1E5
