
exec-once = kanshi
exec-once = swaync

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = pipewire
exec-once = pipewire-pulse
exec-once = wireplumber

exec-once = $term tmux
