
input {
  kb_layout = us,ru
  kb_variant =
  kb_model =
  kb_options = grp:caps_toggle
  kb_rules =
  repeat_rate = 50
  repeat_delay = 300

  sensitivity = $sens #mouse sensitivity
  #accel_profile =     # flat or adaptive or blank or EMPTY means libinput’s default mode
  numlock_by_default = $numlock
  left_handed = $left_handed
  follow_mouse = 1
  float_switch_override_focus = false

  touchpad {
    disable_while_typing = true
    natural_scroll = $nscroll
    clickfinger_behavior = false
    middle_button_emulation = false
    tap-to-click = true
    drag_lock = false
  }

  touchdevice {
  	enabled = true
  }

  tablet {
  	transform = 0
  	left_handed = 0
  }
}


gestures {
  gesture = 3, horizontal, workspace
  workspace_swipe_distance = 500
  workspace_swipe_invert = true
  workspace_swipe_min_speed_to_force = 30
  workspace_swipe_cancel_ratio = 0.5
  workspace_swipe_create_new = true
  workspace_swipe_forever = true
  #workspace_swipe_use_r = true #uncomment if wanted a forever create a new workspace with swipe right

#  gesture = 4, up, dispatcher, exec, hyprctl keyword cursor:zoom_factor "$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor * 1.5}')"
#  gesture = 5, down, dispatcher, exec, hyprctl keyword cursor:zoom_factor "$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor / 1.5}')"
#  gesture = 3, up, dispatcher, exec, $scriptsDir/OverviewToggle.sh
}

scrolling {
    fullscreen_on_one_column = true
    focus_fit_method = 1
    column_width = 0.5
    follow_focus = true
    follow_min_visible = 0.0
    explicit_column_widths = 0.35, 0.5, 0.65, 1.0
}
