
#######################
###   Adding tags   ###
#######################

# notif tags
windowrule = match:class ^(swaync-control-center|swaync-notification-window|swaync-client|class)$, tag +notifindowrule = match:class ^(zen-alpha|zen)$, tag +browser

# browser tags
windowrule = match:class ^([Ff]irefox|org.mozilla.firefox|[Ff]irefox-esr|[Ff]irefox-bin)$, tag +browser
windowrule = match:class ^([Gg]oogle-chrome(-beta|-dev|-unstable)?)$, tag +browser
windowrule = match:class ^(chrome-.+-Default)$, tag +browser
windowrule = match:class ^([Cc]hromium)$, tag +browser
windowrule = match:class ^([Mm]icrosoft-edge(-stable|-beta|-dev|-unstable))$, tag +browser
windowrule = match:class ^(Brave-browser(-beta|-dev|-unstable)?)$, tag +browser
windowrule = match:class ^([Tt]horium-browser|[Cc]achy-browser)$, tag +browser
windowrule = match:class ^(zen-alpha|zen|zen-browser)$, tag +browser

# messenger tags
windowrule = match:class ^([Dd]iscord|[Ww]ebCord|[Vv]esktop)$, tag +im
windowrule = match:class ^([Ff]erdium)$, tag +im
windowrule = match:class ^([Ww]hatsapp-for-linux)$, tag +im
windowrule = match:class ^(org.telegram.desktop|io.github.tdesktop_x64.TDesktop)$, tag +im

# viewer tags
windowrule = match:class ^(gnome-system-monitor|org.gnome.SystemMonitor|io.missioncenter.MissionCenter)$, tag +viewer
windowrule = match:class ^(evince|org.gnome.evince)$, tag +viewer
windowrule = match:class ^(eog|org.gnome.Loupe)$, tag +viewer

# system tags
windowrule = match:class ^(transmission-qt)$, tag +sys
windowrule = match:class ^(blueman-manager)$, tag +sys
windowrule = match:class ^(org.gnome.Calculator)$, tag +sys
windowrule = match:class ^(nwg-displays)$, tag +sys
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, tag +sys
windowrule = match:class ^(KeePassXC)$, tag +sys

# dialogs tags
windowrule = match:title (Select|Open)( a)? (File|Folder)(s)?, tag +dig
windowrule = match:title File (Operation|Upload)( Progress)?, tag +dig
windowrule = match:title .* Properties, tag +dig
windowrule = match:title Export Image as PNG, tag +dig
windowrule = match:title GIMP Crash Debug, tag +dig
windowrule = match:title Save As, tag +dig
windowrule = match:title Library, tag +dig



#############################
###   Declare new rules   ###
#############################

# layer rule
layerrule = match:namespace rofi, blur on
layerrule = match:namespace notifications, blur on

# opacity
windowrule = match:tag browser, opacity 0.99 0.8
windowrule = match:tag im, opacity 0.99 0.86

# float
windowrule = float true, match:tag sys
windowrule = float true, match:tag dig

# workspaces
windowrule = workspace special:communication, match:tag im
windowrule = workspace 2, match:tag browser



#####################
###   Big rules   ###
#####################

windowrule {
    name = Picture-in-Picture
    match:title = ^(Картинка в картинке)$
    float = on
    move = 72% 7%
    opacity = 0.99 0.99
    pin = on
    keep_aspect_ratio = on
    size = (monitor_w*0.3) (monitor_h*0.3)
}

